### PR TITLE
Logged in players can retrieve there ranking information

### PR DESCRIPTION
**Pull request by Fllorent0D**

### CODE REVIEW

**Comment by gfrenoy** [comment]
Thanks Florent.  But that will not work :-/

"pid" is the internal player identifier and "UniqueIndex" is the external member license number.

Moreover, we need to make this optionally configurable by the API admin because this option does not match what is currently possible on the website.

I mean: on the website, you have to have the admin or classement right to see this information.

**Comment by Fllorent0D** [comment]
Ah ok. Didn't check what was the pid, I thought the player id was based on the player's unique index. 

That info would be great to have from my side. A lot of users want their "provisional" ranking directly in the application but they don't have enough permissions.

**Comment by gfrenoy** [comment]
Sure, the need is obvious but it won't work as proposed...

Two changes are required:

- See in _GetPermissions (tabtapi_helpers.php) to join to the playerinfo table to get the UniqueIndex of the connected player (field "playerinfo.vttl_index").  You can store this in $GLOBALS['auth']->auth along with 'pid'
- Permission to expose this information depends on the instance so we need to add a configuration option for that.  It's fairly simple, you need to check that the option is there in $GLOBALS['site_info'], $GLOBALS['site_info']['allow_own_ranking_info']) as an example.  It must be explicitely set to true ; if not defined, default must be false.

Thanks for your help.

**Comment by Fllorent0D** [comment]
Updated the PR. What do you think about it ? 😊

**Comment by gfrenoy** [comment]
Looks great! Thanks a lot. Will integrate this soon and let you know.

**Comment by Fllorent0D** [comment]
Any idea when it will be integrated ? 😊

**Comment by gfrenoy** [comment]
The good question is "What can I do to help speeding up thing?".

And the answer would be : can you have a look at the portion under ```if ($OnBehalfOf > 0)```, there we may also need to add something (not sure what though, need to look into the details but currently no time to do so...).

**Comment by Fllorent0D** [comment]
Thanks ! Nice work !

**Comment by Fllorent0D** [comment]
Is it deployed on both vttl and afft instance? or is the config set to allow the retrieving of the rankings?

**Comment by gfrenoy** [comment]
Yes it is but the flag (allow_own_ranking_info) was not set.  Just did it now for AFTT.

**Comment by Fllorent0D** [comment]
Tried this morning and I didn't see any changes on my profile. Something might be wrong somewhere

**Comment by Fllorent0D** [comment]
Nevermind it's working

**Comment by gfrenoy** [comment]
My bad, one file was not correctly merged.

Note that I made some more tests and strengthened a bit the required permissions to better match reality (VTTL players shall not have access to this information if they are using the AF API).

There was also a security glitch with the OnBehalfOf that is now fixed.

**Pull request merged**
